### PR TITLE
Multiple regression - practical for Tuesday

### PR DESCRIPTION
**Pull request by EmiliaJarochowska**
This is the first (shorter) practical of the week. 
I think @deniseruijsch might be back from holidays so to even out the work distribution and diversity the input I would like to ask you to go through this and see how long it takes and if it you spot any mistakes.
This will be follow by a longer part with predictions, model selection and fitting non-linear models.
Please only review the practical and skip the lecture. I should have split it but my commits weren't atomic enough so now I can't 😅
Thanks!

### CODE REVIEW

**Comment by EmiliaJarochowska** [comment]
Hi @deniseruijsch @kraaijenbrink do you have time to check this or should I reassign? I would like to add contents for the Thursday practical, but it would be useful to know how long this takes, because Thursday will build upon this.

**Comment by deniseruijsch** [comment]
Hi! 
There is one typo: corellated -> correlated. 
You also say: Re-do the points in Task 2. -> do you mean: redo the points from task 1? I was a bit confused here. 

I think task 1 is fairly straightforward and could take about 20-25 mins. Taks 2 is harder and I think can take at least 30 mins, but you could also spend a lot longer on it if you really try to make the best model.

**Review by kraaijenbrink — COMMENTED** [review]
I just did the exercise up to task 1, but I think that might already be enough for the 45 minutes.

**Comment by EmiliaJarochowska** [comment]
Thank you both! I will keep Task 1 for Tuesday and move Task 2 to Thursday.

**Pull request merged**
